### ISSUE TITLE
Java Equivalent

### ISSUE THREAD

**Issue by vakho10** [acidburn974/Blackmagic#1]
Hello Acidburn974, I am a Java developer and I would like to rewrite this library for Java. I just want a consent or approval from you and also I would like to know if this Black Magic is the concrete (the last) project of this kind.

**Comment by kevinb6e** [comment]
Hello vakho10 thanks for your message. This source code was published by Shynd originally on gamedeception.net which is closed since years ago and the on mmowned. The source code was made open source. I replicated it on GitHub for backup. So feel free to replicate it with Java. 😊

**Comment by vakho10** [comment]
OK :) Thanks for the approval and the information.
